# Generated by Django 2.2.6 on 2020-02-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='reg_date_time',
        ),
    ]
