# Generated by Django 2.2.6 on 2019-10-27 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20191027_1921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='User_profile',
        ),
    ]
