# Generated by Django 2.2.6 on 2019-10-27 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20191028_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
    ]
