# Generated by Django 2.2.6 on 2019-10-28 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20191028_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='group',
        ),
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
    ]
