# Generated by Django 2.2.6 on 2019-10-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20191028_0209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
