# Generated by Django 2.2.6 on 2019-10-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20191028_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='admins',
            new_name='members',
        ),
        migrations.AlterField(
            model_name='group',
            name='batch',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='section',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
