# Generated by Django 2.2.6 on 2020-02-08 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_auto_20200207_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 8, 15, 32, 52, 506925)),
        ),
    ]
